# -*- coding: utf-8 -*-
"""21301261_23_LAB5_Class Task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10vUuI8iAveDQkWW-dMepCE20zk2k9nOH
"""

#Deep in the heart of Eldoria lies the enchanted forest, a place of mystery and magic. Legends speak of an artifact hidden within its depths, a source of power that can change the fate of those who possess it. As a fearless adventurer, you set forth on a quest to find this artifact.
#The forest is a labyrinth of ancient trees and mystical creatures. Your journey begins at the entrance, marked by an old stone arch covered in ivy. Armed with a map, you navigate through the dense foliage, encountering both open paths and impassable thickets.
#Your goal is the elusive artifact, said to be hidden in a cell marked 'A'. To find it, you must carefully choose your path, avoiding blocked areas that may lead you astray. Can you decipher the secrets of the enchanted forest and emerge victorious with the artifact in hand?
forest_map = [
    ['.', '#', '.', '.', '#', '.', '#', '.'],
    ['.', '#', '.', '#', '.', '.', '.', '.'],
    ['.', '#', '.', '#', '#', '#', '#', '.'],
    ['.', '.', '.', '.', 'A', '.', '.', '.']
]
col=len(forest_map)
row=len(forest_map[0])
start=[0,0]
visited=[[False for i in range(len(forest_map[1]))]for j in range(len(forest_map))]
flag=False
def dfs(c,r):
  global flag
  if c<0 or c>=col or r<0 or r>=row or forest_map[c][r]=='#' or visited[c][r]:
    return -1
  else:
    visited[c][r]=True
    if forest_map[c][r]=='A':
      flag = True
    else:
      dfs(c+1,r)
      dfs(c-1,r)
      dfs(c,r+1)
      dfs(c,r-1)
def find_artifact_dfs(grid):
  visited=[[False for i in range(len(forest_map[0]))]for j in range(len(forest_map))]
  temp=dfs(0,0)
  if flag == False:
    return False
  else:
    return True
result = find_artifact_dfs(forest_map)
if result == True:
    print("Congratulations! You found the artifact!")
else:
    print("Alas! The artifact remains elusive.")