# -*- coding: utf-8 -*-
"""21301261_Evaluation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJMPj_oZHTpgp2Zk99Li-2IPWfvAvcHH
"""

def compare(lis1,lis2):
  i=0
  j=0
  finlis=[]
  while i < len(lis1) and j < len(lis2):
    if lis1[i]<lis2[j]:
      i+=1
    elif lis2[j]<lis1[i]:
      finlis.append(len(lis1[:i]))
      j+=1
    elif lis1[i]==lis2[j]:
      finlis.append(len(lis1[:i]))
      j+=1
  if j<len(lis2):
    for j in range (j,len(lis2)):
      finlis.append(len(lis1[:i]))
  return finlis
with open('/content/input.txt','r') as inp:
  with open('/content/output.txt', 'w') as out:
    alicelen=int(inp.readline())
    templis1=(inp.readline().strip()).split(' ')
    boblen=int(inp.readline())
    templis2=(inp.readline().strip()).split(' ')
    alicelis=[]
    boblis=[]
    for i in templis1:
      alicelis.append(int(i))
    for j in templis2:
      boblis.append(int(j))
    temp=compare(alicelis,boblis)
    for i in temp:
      out.write(f'{i} ')